In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv("spam.csv", encoding="latin-1")

In [ ]:
data.head()

,class,message,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [ ]:
data.columns

Index(['class', 'message', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [ ]:
data.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)

In [ ]:
data.head()

  class                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
data['class']=data['class'].map({'ham':0, 'spam':1})

In [ ]:
data.head()

   class                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer()

In [ ]:
x=data['message']
y=data['class']

In [ ]:
x.shape

(5572,)

In [ ]:
y.shape

(5572,)

In [ ]:
x=cv.fit_transform(x)

In [ ]:
x

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 73916 stored elements and shape (5572, 8672)>

1.The Cat 
2.The Dog 
3.The Bird

    The Cat Dog Bird
1.   1   1   0   0
2.   1   0   1   0
3.   1   0   0   1

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2)

In [ ]:
x_test.shape

(1115, 8672)

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model=MultinomialNB()

In [ ]:
model.fit(x_train, y_train)

MultinomialNB()

In [ ]:
result=model.score(x_test, y_test)

In [ ]:
result=result*100

In [ ]:
result

98.02690582959642

In [ ]:
import pickle

In [ ]:
pickle.dump(model, open("spam.pkl","wb"))

In [ ]:
pickle.dump(cv, open("vectorizer.pkl","wb"))

In [ ]:
clf=pickle.load(open("spam.pkl","rb"))

In [ ]:
clf

MultinomialNB()

In [ ]:
msg="You won 10 dollar"
data=[msg]
vect=cv.transform(data).toarray()
result=model.predict(vect)
print(result)

[1]